# Generated by Django 3.2.5 on 2023-10-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwitter', '0002_dweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='dweet',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
